server:
  port: 8000
eureka:
  client:
    #是否将自己注册到eurekaServer
    register-with-eureka: false
    #是否从eureka server获取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka/
  server:
    #关闭自我保护机制
    enable-self-preservation: false
spring:
  application:
    name: zhihu-eureka